# Generated by Django 2.1.3 on 2018-12-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='node_name')),
                ('node', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='node_id')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=False, to='core.Tree', verbose_name='parent_id')),
            ],
            options={
                'verbose_name': '树',
                'ordering': ['node'],
            },
        ),
    ]
